#+TITLE: Protocol

1) An Unrival object (hereinafter simply referred to as /an object/) satisfies all of the following conditions:
2) An object is uniquely determined by an address.
3) A name is a possibly non-unique, humanly-readable way of referring to an object.
4) An interpretation is a hierarchical ordering of names.
5) A universe is a mapping from interpretations to addresses.
6) A proof is an object which, given another object and within a certain universe, is either satisfied by or not satisfied by this other object.
7) If an object references a proof, it must satisfy this proof.   
8) An ancestor is an object from which another object inherits, such that the inheriting object must satisfy any proofs referenced by its ancestor(s) in addition to those it references directly.   
9) A namespace is a set of names that can be considered equivalent for some purpose.
10) An object must reference a universe in which any ancestors it references may be interpreted.
10) If an object references a namespace, 
